# Targets
LLVM_LL=msp430g2xx3_P1_01.ll blink.ll  msp430g2x33_adc10_01.ll interrupt-test.ll
LLVM_BITCODES=msp430g2xx3_P1_01.bc blink.bc  msp430g2x33_adc10_01.bc interrupt-test.bc

# Please set your device here
CHIP = msp430g2553
include ../Makefile.defs

