all:
	../../plugin_gen/scripts/build.py .

clean:
	../../plugin_gen/scripts/build.py . clean

fuzz:
	../../plugin_gen/scripts/build.py . fuzz

reset:
	../../plugin_gen/scripts/build.py . reset
	make all
